CREATE OR REPLACE VIEW odk_prod.hab_forms_datageom AS
SELECT 
  ROW_NUMBER() OVER () AS id,
  "FI_HAB_SURVEY_T0_CORE"."WAYPOINT" AS waypoint_id, 
  "FI_HAB_SURVEY_T0_CORE"."_URI" AS uri,
  "FI_HAB_SURVEY_T0_CORE"."DATE_TIME" AS date_time, 
  "FI_HAB_SURVEY_T0_CORE"."NOTES_GEOMORPH" AS geomorphology_notes,
  "FI_HAB_SURVEY_T0_CORE"."HABITAT_YES_NO" AS is_a_mosaic,
  "FI_HAB_SURVEY_T0_CORE"."HABITAT_LEVEL" AS hab_sensor,
  "FI_HAB_SURVEY_T0_CORE"."HABITAT_HABITAT_TYPE1" AS habitat_s2,
  "FI_HAB_SURVEY_T0_CORE"."HABITAT_HABITAT_TYPE2" AS habitat_ww3,
  "FI_HAB_SURVEY_T0_CORE"."HABITAT_HABITAT_TYPE3" AS habitat_drone,
  "FI_HAB_SURVEY_T0_CORE"."MOSAIC_SCALE" AS mosaic_sensor,
  "FI_HAB_SURVEY_T0_CORE"."MOSAIC_MOSAIC1" AS mosaic1_s2,
  "FI_HAB_SURVEY_T0_CORE"."MOSAIC_COVERAGE1" AS mosaic1_s2_pcent,
  "FI_HAB_SURVEY_T0_CORE"."MOSAIC_MOSAIC2" AS mosaic2_s2,
  "FI_HAB_SURVEY_T0_CORE"."MOSAIC_COVERAGE2" AS mosaic2_s2_pcent,
  "FI_HAB_SURVEY_T0_CORE"."MOSAIC_MOSAIC3" AS mosaic3_s2,
  "FI_HAB_SURVEY_T0_CORE"."MOSAIC_COVERAGE3" AS mosaic3_s2_pcent,
  "FI_HAB_SURVEY_T0_CORE"."MOSAIC_MOSAIC4" AS mosaic4_s2,
  "FI_HAB_SURVEY_T0_CORE"."MOSAIC_COVERAGE4" AS mosaic4_s2_pcent,
  "FI_HAB_SURVEY_T0_CORE"."MOSAIC_TOTAL_COVERAGE" AS mosaic_s2_totpcent,
  "FI_HAB_SURVEY_T0_CORE"."MOSAIC_MOSAIC5" AS mosaic5_ww3,
  "FI_HAB_SURVEY_T0_CORE"."MOSAIC_COVERAGE5" AS mosaic5_ww3_pcent,
  "FI_HAB_SURVEY_T0_CORE"."MOSAIC_MOSAIC6" AS mosaic6_ww3,
  "FI_HAB_SURVEY_T0_CORE"."MOSAIC_COVERAGE6" AS mosaic6_ww3_pcent,
  "FI_HAB_SURVEY_T0_CORE"."MOSAIC_MOSAIC7" AS mosaic7_ww3,
  "FI_HAB_SURVEY_T0_CORE"."MOSAIC_COVERAGE7" AS mosaic7_ww3_pcent,
  "FI_HAB_SURVEY_T0_CORE"."MOSAIC_MOSAIC8" AS mosaic8_ww3,
  "FI_HAB_SURVEY_T0_CORE"."MOSAIC_COVERAGE8" AS mosaic8_ww3_pcent,
  "FI_HAB_SURVEY_T0_CORE"."MOSAIC_TOTAL_COVERAGE2" AS mosaic_ww3_totpcent,
  "FI_HAB_SURVEY_T0_CORE"."NOTES_HABITAT" AS notes_hab_mosaic,
  "FI_HAB_SURVEY_T0_CORE"."CONFIDENCE_LEVEL" AS confidence_level,
  'media/' || "FI_HAB_SURVEY_T0_PHOTOS_PICTURE_EAST_BN"."UNROOTED_FILE_PATH" AS picture_east,
  'media/' || "FI_HAB_SURVEY_T0_PHOTOS_PICTURE_SOUTH_BN"."UNROOTED_FILE_PATH" AS picture_south,
  'media/' || "FI_HAB_SURVEY_T0_PHOTOS_PICTURE_WEST_BN"."UNROOTED_FILE_PATH" AS picture_west,
  'media/' || "FI_HAB_SURVEY_T0_PHOTOS_PICTURE_NORTH_BN"."UNROOTED_FILE_PATH" AS picture_north,
  'media/' || "FI_HAB_SURVEY_T0_PHOTOS_PICTURE_GROUND_BN"."UNROOTED_FILE_PATH" AS picture_ground,
  waypoints.geom AS geom
FROM
  odk_prod."FI_HAB_SURVEY_T0_CORE", 
  odk_prod."FI_HAB_SURVEY_T0_PHOTOS_PICTURE_EAST_BN", 
  odk_prod."FI_HAB_SURVEY_T0_PHOTOS_PICTURE_GROUND_BN", 
  odk_prod."FI_HAB_SURVEY_T0_PHOTOS_PICTURE_NORTH_BN", 
  odk_prod."FI_HAB_SURVEY_T0_PHOTOS_PICTURE_SOUTH_BN", 
  odk_prod."FI_HAB_SURVEY_T0_PHOTOS_PICTURE_WEST_BN",
  odk_prod.waypoints
WHERE 
  "FI_HAB_SURVEY_T0_CORE"."WAYPOINT" = waypoints.name AND
  "FI_HAB_SURVEY_T0_CORE"."_URI" = "FI_HAB_SURVEY_T0_PHOTOS_PICTURE_EAST_BN"."_PARENT_AURI" AND
  "FI_HAB_SURVEY_T0_CORE"."_URI" = "FI_HAB_SURVEY_T0_PHOTOS_PICTURE_GROUND_BN"."_PARENT_AURI" AND
  "FI_HAB_SURVEY_T0_CORE"."_URI" = "FI_HAB_SURVEY_T0_PHOTOS_PICTURE_NORTH_BN"."_PARENT_AURI" AND
  "FI_HAB_SURVEY_T0_CORE"."_URI" = "FI_HAB_SURVEY_T0_PHOTOS_PICTURE_WEST_BN"."_PARENT_AURI" AND
  "FI_HAB_SURVEY_T0_CORE"."_URI" = "FI_HAB_SURVEY_T0_PHOTOS_PICTURE_SOUTH_BN"."_PARENT_AURI";
